### ISSUE TITLE
Devel Themer module whitescreens when when enabled

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/cu_debug_admin_bundle#6]
Discussion: https://www.drupal.org/project/devel_themer/issues/2789091

**Comment by jwfuller** [comment]
@cathysnider It seems like the summary of that conversation is to get rid of the module and use a work-around. That seems reasonable to me, what do you think?

**Comment by cathysnider** [comment]
Yes. Devel Themer is not workable. There's no point in keeping it in the package.
